---
hosts:
  -
    box: Makr44/ubuntu2104-server
    ## Descriptors
    name: session-observer-01.prominic.work
    parition_id: "0000"
    vmtype: production

    ## VM Resources
    #cpu_configuration: complex
    cpu_configuration: simple
    simple_vcpu_conf: 4
    complex_cpu_conf:
      - 
        sockets: 2
        cores: 4
        threads: 2
   
    memory: 512M

    ## VM settings
    autostart: true
    brand: bhyve
    firmware_type: compatability
    acpi: on
    os_type: generic
    diskif: virtio-blk
    netif: virtio-net-viona
    hostbridge: i440fx

    ## Cloud-init
    cloud_init_enabled: true

    ## Disk
    zonepath: /Array-0/zones
    rootdisksize: 40G

    ## Networking
    bridge1: igb0
    bridge2: igb0
    ip1: 192.168.2.137
    ip2: 192.168.2.138
    type1: external
    type2: internal
    managed1: true
    managed1: false
    vlan1: nil
    vlan2: nil
    mac1: 52:54:0f:c9:cf:12
    mac2: 52:54:0f:c9:cf:14
    gateway1: 192.168.2.1
    gateway2: 192.168.2.1
    netmask1: 255.255.0.0
    netmask2: 255.255.0.0
    dhcp: false

    ## DNS
    nameserver1: 1.1.1.1
    nameserver2: 1.0.0.1

    ## Shared Mounted Disk -- NotYetImplemented
    shared_lofs_disk_enabled: false
    shared_lofs_dir: '../example-provisioner-scripts/ansible/'

    ## Emergency Console Access
    vnc: false
    console: false

    ### Provisioning
    ## clone branch of repo
    branch:

    ## Provisioning Settings
    setup_wait: 30
    clean_shutdown_time: 200
    ansible_provision: true
    ansible_provision_scripts:
      - ../../example-provisioner-scripts/ansible/conf/Setup.yml
    shell_provision: false
    provision:
      - "./scripts/aliases.sh"

     ## User Configurations
    vagrant_user_private_key_path: ./id_rsa
    vagrant_user: prominic
    #vagrant_user_pass: XXXXXXX
    vagrant_insert_key: false

    ## Synced Folders
    folders:
      -
        map: ../../example-provisioner-scripts/ansible/
        to: /vagrant

    disks:
      -
        array: Array-1
        dataset: /vagrant-1
        size: 40G
      -
        Array: Array-0
        dataset: /vagrant-0
        size: 40G
    networks:
      -
        address: 192.168.2.137
        netmask: 255.255.255.0
        gateway: 192.168.2.1
        mac: 52540fc9cf14
        vlan: nil
        bridge: igb0
        type: external
        is_control: true
      -
        address: 192.168.2.136
        netmask: 255.255.255.0
        gateway: 192.168.2.1
        mac: 52540fc9cf12
        vlan: nil
        bridge: igb0
        type: external
        is_control: false
    dns:
      -
        nameserver1: 1.1.1.1
        nameserver2: 1.0.0.1
#   provider:
#     -
#       directive: memory
#       value: "8096"
#     -
#       directive: cpus
#       value: "4"
path: "."
