---
hosts:
  -
    box: Makr44/ubuntu2104-server
    boxshortname:  ubuntu2104-server
    cloud_creator: Makr44
    ## Descriptors
    name: MyUniqueVMName-usuallyaFQDN
    partition_id: "0000"
    vmtype: production

    ## VM Resources
    ## complex / simple
    cpu_configuration: simple
    
    simple_vcpu_conf: 4
    complex_cpu_conf:
      - 
        sockets: 2
        cores: 4
        threads: 2
   
    memory: 4G

    ## VM settings
    autostart: true
    ## ipkg / lipkg / sparse / pkgsrc / lx / bhyve (default) / kvm / illumos
    brand: bhyve
    ## UEFI, BIOS, compatability, BHYVE_DEBUG
    firmware_type: UEFI
    acpi: on
    ## generic (default) / openbsd / windows
    os_type: generic
    ## ahci / virtio (default)
    diskif: virtio-blk
    ## virtio-net-pci (default) / e1000
    netif: virtio-net-viona
    ## 
    hostbridge: i440fx
    ## Login Check String via zlogin
    lcheck_string: ':~'
    ## Automatic Login Check String used to detect if we need to enter a password to access the console via zlogin
    alcheck_string: "login:"
    ## Used to show the boot sequence
    debug_boot: true
    ## Used to show more info
    debug: true

    safe_restart: 'sudo shutdown -r'
    safe_shutdown: 'sudo init 0 || true'

    ## Configuration Method, zlogin/dhcp
    setup_method: zlogin

    ## Cloud-init
    cloud_init_enabled: off
    ## Uncomment conf if using a URL or File for Userdata
    cloud_init_conf: on
    cloud_init_dnsdomain: int.dc-01.m4kr.net

    ## Disk
    boot:
      array: Array-0
      dataset: zones
      volume_name: boot
      size: 15G
      sparse: true

    additional_disks:
#      -
#        array: Array-1
#        dataset: zones
#        volume_name: disk1
#        size: 40G
#        sparse: true
#        live: yes
    cdroms:
#      -
#        path: /path/to/your/example.iso

    ## Networking
    networks:
      -
        address: 192.168.2.187
        netmask: 255.255.255.0
        gateway: 192.168.2.1
        mac: 52:54:0f:c9:c1:15
        vlan: 
        dhcp4: no
        dhcp6: no
        bridge: igb0
        type: external
        is_control: true
      -
        address: 192.168.2.191
        netmask: 255.255.255.0
        gateway: 192.168.2.1
        mac: 52:54:0f:c9:d1:15
        vlan: 
        dhcp4: no
        dhcp6: no
        bridge: ixgbe0
        type: nat
        is_control: true
#      -
#        address: 192.168.5.186
#        netmask: 255.255.255.0
#        gateway: 192.168.5.1
#        mac: 52:54:0f:c9:c1:17
##        vlan: 
#        dhcp4: no
#        dhcp6: no
#        bridge: igb0
#        type: external
#        is_control: false
    ## DNS
    dns:
      -
        nameserver: 1.1.1.1
      -
        nameserver: 1.0.0.1

    ## Shared Mounted Disk -- NotYetImplemented
    shared_lofs_disk_enabled: false
    shared_lofs_dir: '../example-provisioner-scripts/ansible/'

    # Script Used for Snapshots
    snapshot_script: '/opt/vagrant/bin/Snapshooter.sh'

    ## Emergency Console Access -- webvnc -- vnc -- console -- disabled (zlogin)
    console_onboot: false
    console: webvnc
    consoleport: 7900
    consolehost: 0.0.0.0

    ### Provisioning
    ## clone branch of repo
    branch:

    ## Provisioning Settings
    setup_wait: 60
    clean_shutdown_time: 200
    ansible_provision: true
    ansible_provision_scripts:
      -
        local: 
          - 
            script: conf/Setup.yml
            ansible_python_interpreter: /usr/bin/python3
            compatibility_mode: 2.0
            install_mode: pip
      -
        remote: 
          - 
            script: ../../example-provisioner-scripts/ansible/conf/Setup.yml
            ansible_python_interpreter: /usr/bin/python3
            compatibility_mode: 2.0
            install_mode: pip
    shell_provision: false
    provision_scripts:
      - "./scripts/aliases.sh"

     ## User Configurations
    vagrant_user_private_key_path: ./id_rsa
    vagrant_user: prominic
    #vagrant_user_pass: XXXXXXX
    vagrant_insert_key: false

    ## Synced Folders
    folders:
      -
        map: ../../example-provisioner-scripts/ansible/
        to: /vagrant
path: "."
