---
hosts:
  -
    box: Makr44/ubuntu2104-server
    ## Descriptors
    name: session-observer-01.prominic.work
    parition_id: "0000"
    vmtype: production

    ## VM Resources
    cpu_configuration: complex
    #cpu_configuration: simple
    simple_vcpu_conf: 4
    complex_cpu_conf:
      - 
        sockets: 2
        cores: 4
        threads: 2
   
    memory: 1G

    ## VM settings
    autostart: true
    ## ipkg / lipkg / sparse / pkgsrc / lx / bhyve (default) / kvm / illumos
    brand: bhyve
    firmware_type: compatability
    acpi: on
    ## generic (default) / openbsd / windows
    os_type: generic
    ## ahci / virtio (default)
    diskif: virtio-blk
    ## virtio-net-pci (default) / e1000
    netif: virtio-net-viona
    ## 
    hostbridge: i440fx

    ## Cloud-init
    cloud_init_enabled: false

    ## Disk
    zonepath: /Array-0/zones
    rootdisksize: 40G
    additional_disks:
#      -
#        array: Array-0
#        path: /vagrant-1
#        size: 40G
    cdroms:
#      -
#        path: /opt/ooce/ruby-2.7/lib/ruby/gems/2.7.0/bundler/gems/vagrant-spec-03d88fe24677/acceptance/support-skeletons/disk_dvd/example.iso
#      -
#        path: /home/mvcs/prominic-philotic-packer-templates/packer_cache/ffca25fa2718072c7ba900c6a966e53224591dab.iso
    ## Networking
    bridge1: igb0
    bridge2: igb0
    ip1: 192.168.2.187
    ip2: 192.168.2.188
    type1: external
    type2: internal
    managed1: true
    managed2: false
    vlan1: nil
    vlan2: nil
    mac1: 52:54:0f:c9:cf:12
    mac2: 52:54:0f:c9:cf:14
    gateway1: 192.168.2.1
    gateway2: 192.168.2.1
    netmask1: 255.255.0.0
    netmask2: 255.255.0.0
    dhcp4-1: false
    dhcp4-2: true
    dhcp6-1: false
    dhcp6-2: false
    networks:
      -
        address: 192.168.2.187
        netmask: 255.255.255.0
        gateway: 192.168.2.1
        mac: 52540fc9cf14
        vlan: nil
        dhcp4: false
        dhcp6: false
        bridge: igb0
        type: external
        is_control: true
      -
        address: 192.168.2.186
        netmask: 255.255.255.0
        gateway: 192.168.2.1
        mac: 52540fc9cf12
        vlan: nil
        dhcp4: false
        dhcp6: false
        bridge: igb0
        type: external
        is_control: false
    #
    #    override: false

    ## DNS
    dns:
      -
        nameserver: 1.1.1.1
      -
        nameserver: 1.0.0.1

    ## Shared Mounted Disk -- NotYetImplemented
    shared_lofs_disk_enabled: false
    shared_lofs_dir: '../example-provisioner-scripts/ansible/'

    ## Emergency Console Access -- webvnc -- vnc -- console -- disabled (zlogin)
    console_onboot: false
    console: webvnc
    consoleport: 7900

    ### Provisioning
    ## clone branch of repo
    branch:

    ## Provisioning Settings
    setup_wait: 30
    clean_shutdown_time: 200
    ansible_provision: true
    ansible_provision_scripts:
      - ../../example-provisioner-scripts/ansible/conf/Setup.yml
    shell_provision: false
    provision:
      - "./scripts/aliases.sh"

     ## User Configurations
    vagrant_user_private_key_path: ./id_rsa
    vagrant_user: prominic
    #vagrant_user_pass: XXXXXXX
    vagrant_insert_key: false

    ## Synced Folders
    folders:
      -
        map: ../../example-provisioner-scripts/ansible/
        to: /vagrant
path: "."
